"""empty message

Revision ID: a1d65176b4ff
Revises: 92f282ed73d7
Create Date: 2021-03-30 01:31:04.486539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1d65176b4ff'
down_revision = '92f282ed73d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('slug', sa.String(), nullable=True))
    op.add_column('post', sa.Column('title', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'title')
    op.drop_column('post', 'slug')
    # ### end Alembic commands ###
